name: Deploy

on: 
  pull_request:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout backend
      uses: actions/checkout@v3

    - name: Deploy backend to EC2
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOSTNAME }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: "/home/ec2-user/"
          SCRIPT_AFTER: |
            yarn
            yarn build
            yarn start:prod

  deploy-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout frontend
      uses: actions/checkout@v3

    - name: Deploy frontend to EC2
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOSTNAME }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: "/home/ec2-user/"
          SCRIPT_AFTER: |
            yarn
            yarn start